description: "Этот бот поможет вам следить за днями рождения ваших друзей. Проверьте меню, чтобы увидеть доступные функции"
messages:
  enter_name: "Введите имя человека."
  enter_birthday_date: "Введите дату дня рождения в формате `dd-mm-yyyy`, например, 02-10-1999."
  enter_reminder_days: "Введите количество дней до напоминания."
  enter_gifts: "Введите подарки, которые попросил именинник."
  enter_note: "Введите небольшую заметку (например, чтобы указать дату и время празднования)."
  added_birthday: "Добавлено напоминание о дне рождения для {name} на {birthday_date} с напоминанием за {reminder_days} дней. Подарки: {gifts}. Заметка: {note}."
  your_reminders: "Ваши напоминания:"
  no_reminders: "У вас нет активных напоминаний."
  birthday_reminder: "Имя именинника: {name} на {birthday_date} с напоминанием за {reminder_days} дней. Подарки: {gifts}. Заметка: {note}."