version: 1
formatters:
  simple:
    format: "%(message)s"
  json:
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
  json:
    class: logging.StreamHandler
    formatter: json
    level: INFO

loggers:
  __main__:
    level: INFO
    handlers: [console, json]
    propagate: no

root:
  level: INFO
  handlers: [console, json]
